dias = int(input('Quantos dias? '))
horas = int(input('Quantas horas? '))
minutos = int(input('Quantos minutos? '))
segundos = int(input('Quantos segundos? '))
calculo = segundos + (minutos * 60) + (horas * 3600) + (dias * 86400)
print(f'Total em segundos: {calculo}')
